// GENERATED by scripts/gen-blur.mjs — do not edit by hand.
export const blurData = {
  "/images/about-hero.webp": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoMAAgABUB8JQBOgBZ51hibAAD765ZVR/chtP5ypqdp9VvGLL9g8neFo58yyCQmhfOnwEOcFEJulUAA",
  "/images/blog-hero.webp": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAQCdASoMAAgABUB8JZwAAl3WchxyoAD+BmqcoFF3me8kqgWq36qjFBE9hj1Cck5XAAAA",
  "/images/blog2.webp": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoMAAkABUB8JZQAAp+uwblDgADOPkBo9RsDgz1SjUtFremE0rf87GJz21O+hjbwSffoMZbJdkAOAA==",
  "/images/contact-hero.webp": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoMAAgABUB8JYwAAsQzLASAAP6RgVl0zztDGoCcB4oTxiisZztVN/Px3v5/5CdG22tpYxYUAAA=",
  "/images/main-hero.webp": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoMAAgABUB8JZwAAxSgB/8W4AD+52fQTXWir3d2A9uKW2kWRh4gBNvHTbqpOcPZ9teBAAAA",
  "/images/patiala-hero.webp": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoMAAgABUB8JZQAAloUp9kwAPl8S5HqSfJ4/O1+VlYFj/YwMWRLoCFdUoapx7PBOLILD6IHAAA=",
  "/images/portfolio-hero.webp": "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAACQAQCdASoMAAgABUB8JaQAAtz5KtAA/u1DdSytc3I4G2J1AAA=",
  "/images/privacy-hero.webp": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAQCdASoMAAsABUB8JQBOgBt1ZnhsAAD+Ft1QP+6X92okKc9TYXbtdg3rj/77/Sm9IDcLGr2tQ3GaiVwXuKwCkcm7Luy5YjMaAAAA",
  "/images/services/custom-hero.webp": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoMAAgABUB8JZwAAloEnJ+lwAD+4gumLQ63vRUlFfH8ab4k47MPJgL/3BYi5GgQAAA=",
  "/images/services/ecommerce-hero.webp": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAABQAwCdASoMABIAPzmGuVOvKSWisAgB4CcJYwDLLBwvjvFu6AD+3ufQexcbrLNu4ICyOISeaucIUrjAUQ8/j0qq1E58uQT8AAA=",
  "/images/services/maintain-hero.webp": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACQAQCdASoMAAkABUB8JZwAAeGvLpAAziQ3PNE6ddPjD832hVtCt5ZjKBY7bfcSPKIUVtGbBIAAAA==",
  "/images/services/seo-hero.webp": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoMAAgABUB8JQBOgCHhJMaXF4AA/oOY4B2B9lC+sKe2mGBXeHLjWQzrN/wvmtZXvKvXQAAA",
  "/images/terms-hero.webp": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACwAQCdASoMAAgABUB8JZQAAty3W+aAAP7eH5Iucal6q8Air6C4oLz7jzV8haAcQp2cLc2KdvQgAA==",
  "/images/webdev-hero.webp": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoMAAgABUB8JYwAAfbTFLXUAAD+7W03erTf8mBUbki1yW4yyyBLS1gyU+BzbVxrCsZqm2wBYxAAAA=="
}
