// Client testimonials data for EaseBuilds - Best Web Developer in Patiala Punjab India
// Optimized for local SEO with review schema

export const clientReviews = [
  {
    id: 1,
    name: 'Tanishq Modgill',
    role: 'Director',
    business: 'Modgill Travels',
    location: 'Patiala Punjab India',
    avatar: '/images/clients/tanishq.jpg',
    rating: 5,
    review: 'EaseBuilds built an amazing booking website for our travel agency in Patiala. Real-time availability and payment integration work perfectly. Bookings have increased by 50%! Excellent web development company in Patiala with modern technology. Highly recommended!',
    project: 'Travel Booking Website',
    date: '2024-03-10',
    featured: true,
  },
  {
  id: 2,
  name: 'Manish Panwar',
  role: 'Managing Director',
  business: 'Tapeindia Manufacturing',
  location: 'Chennai India',
   avatar: '/images/clients/manish.jpg',
  rating: 5,
  review: 'EaseBuilds transformed our tape manufacturing business online presence in Patiala. Our new B2B website showcases our product catalog professionally and we started receiving bulk inquiries from distributors across India within 2 weeks. Their expertise in industrial website development and local SEO helped us rank on Google for tape manufacturers in Punjab. Highly recommended web developer in Patiala!',
  project: 'B2B Manufacturing Website',
  date: '2024-11-20',
  featured: true,
},
{
  id: 3,
  name: 'Manveer Chauhan',
  role: 'Founder & Director',
  business: 'Pariksha Coaching Institute',
  location: 'Patiala Punjab India',
   avatar: '/images/clients/manveer.jpg',
  rating: 5,
  review: 'EaseBuilds developed an outstanding website for our coaching institute in Patiala with online admission forms, course catalog, and student portal. Within one month, our online registrations increased by 300%! The mobile-friendly design and fast loading speed impressed our students and parents. They truly understand education sector needs. Best web development service in Patiala Punjab India!',
  project: 'Coaching Institute Website with Student Portal',
  date: '2024-10-28',
  featured: true,
},
  {
    id: 4,
    name: 'Architect Simran Kaur',
    role: 'Principal Architect',
    business: 'Kaur Architects',
    location: 'Patiala Punjab India',
    avatar: '/images/clients/simran.jpg',
    rating: 5,
    review: 'Outstanding work by EaseBuilds! They built a beautiful portfolio website for our architecture firm in Patiala. The gallery section perfectly showcases our projects. Professional web development company with amazing design skills. Highly recommended for businesses in Patiala!',
    project: 'Architecture Portfolio Website',
    date: '2024-11-20',
    featured: true,
  },
  {
    id: 5,
    name: 'Manpreet Singh',
    role: 'Managing Director',
    business: 'Singh Manufacturing',
    location: 'Patiala Punjab India',
    avatar: '/images/clients/manpreet.jpg',
    rating: 5,
    review: 'We needed an e-commerce website for our valve manufacturing business in Patiala. EaseBuilds delivered exactly what we wanted - fast loading, clean design, and easy product catalog management. Sales have increased by 40% since launch. Top website development company in Patiala!',
    project: 'Manufacturing E-commerce Site',
    date: '2024-10-05',
    featured: true,
  },
  {
    id: 6,
    name: 'Mrs. Neha Sharma',
    role: 'Director',
    business: 'Bright Minds Coaching',
    location: 'Patiala Punjab India',
    avatar: '/images/clients/neha.jpg',
    rating: 5,
    review: 'EaseBuilds transformed our coaching institute website in Patiala. The online admission form and course details section work flawlessly. Student inquiries have doubled! Fast delivery, affordable pricing, and excellent support. Best choice for educational institutions in Patiala Punjab India.',
    project: 'Coaching Institute Website',
    date: '2024-09-12',
    featured: true,
  },
  {
    id: 7,
    name: 'Dr. Amrit Patel',
    role: 'Healthcare Consultant',
    business: 'Patel Medical Center',
    location: 'Patiala Punjab India',
    avatar: '/images/clients/amrit.jpg',
    rating: 5,
    review: 'EaseBuilds built a comprehensive website for our medical center in Patiala with online appointment booking and patient portal. The design is professional and the website loads super fast. Best website design company in Patiala Punjab India. Highly satisfied!',
    project: 'Medical Center Website',
    date: '2024-07-18',
    featured: true,
  },
  {
    id: 8,
    name: 'Jaskaran Singh Gurm',
    role: 'Proprietor',
    business: 'Bhatti Real Estate',
    location: 'Patiala Punjab India',
    avatar: '/images/clients/jaskaran.jpg',
    rating: 5,
    review: 'Excellent web development service in Patiala! EaseBuilds created a property listing website for our real estate business with advanced search filters. Lead generation has increased significantly. Fast, professional, and affordable. Top web developer in Patiala!',
    project: 'Real Estate Website',
    date: '2024-06-30',
    featured: false,
  },
  {
    id: 9,
    name: 'Jyoti Malhotra',
    role: 'Owner',
    business: 'Malhotra Boutique',
    location: 'Patiala Punjab India',
    avatar: '/images/clients/jyoti.jpg',
    rating: 5,
    review: 'EaseBuilds designed a beautiful e-commerce website for our boutique in Patiala. The product showcase is elegant and checkout is smooth. We are getting online orders from across Punjab! Best web design company in Patiala with creative designers.',
    project: 'Boutique E-commerce Site',
    date: '2024-05-14',
    featured: true,
  },
  {
    id: 10,
    name: 'Dr. Rajesh Kumar',
    role: 'Dental Surgeon',
    business: 'Kumar Dental Clinic',
    location: 'Patiala Punjab India',
    avatar: '/images/clients/rajesh.jpg',
    rating: 5,
    review: 'EaseBuilds created a stunning website for our dental clinic in Patiala. Within the first week, we started receiving online appointment bookings. Their team understood our needs perfectly and delivered a mobile-friendly website that ranks on Google. Best web developer in Patiala Punjab India!',
    project: 'Dental Clinic Website',
    date: '2024-12-15',
    featured: true,
  },
]

// Generate review schema for SEO
export function generateReviewSchema(review) {
  return {
    '@type': 'Review',
    author: {
      '@type': 'Person',
      name: review.name,
    },
    datePublished: review.date,
    reviewBody: review.review,
    reviewRating: {
      '@type': 'Rating',
      ratingValue: review.rating,
      bestRating: 5,
      worstRating: 1,
    },
    itemReviewed: {
      '@type': 'LocalBusiness',
      name: 'EaseBuilds',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Patiala',
        addressRegion: 'Punjab',
        addressCountry: 'IN',
      },
    },
  }
}

export default clientReviews
