// Generates tiny inline blur placeholders for hero images.
//
// Run after adding or replacing a hero image:  node scripts/gen-blur.mjs
//
// ponytail: a committed generated file, not a webpack loader or a build hook.
// Heroes change a few times a year; a script you re-run is less machinery than
// a plugin that runs on every build forever.
import sharp from 'sharp'
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs'
import { join, sep } from 'node:path'

// Only images used as a page hero — these are the ones that pop in behind text.
// Below-fold images don't need this; they lazy-load off-screen where nobody sees it.
const HERO = new Set([
  'main-hero', 'about-hero', 'blog-hero', 'blog2', 'contact-hero', 'patiala-hero',
  'portfolio-hero', 'privacy-hero', 'terms-hero', 'webdev-hero',
  'industries/architect/hero', 'industries/coaching/coaching-hero',
  'industries/dental/dental-hero', 'industries/manufacturer/invoice',
  'industries/retail/hero',
  'services/custom-hero', 'services/ecommerce-hero', 'services/maintain-hero', 'services/seo-hero',
])

function walk(dir, acc = []) {
  for (const e of readdirSync(dir)) {
    const p = join(dir, e)
    statSync(p).isDirectory() ? walk(p, acc) : acc.push(p)
  }
  return acc
}

const out = {}
const missing = new Set(HERO)

for (const file of walk('public/images')) {
  if (!file.endsWith('.webp')) continue
  const key = file.split(sep).join('/').replace('public/images/', '').replace('.webp', '')
  if (!HERO.has(key)) continue
  missing.delete(key)
  // 12px wide is enough to read as "the right colours are here" once blurred
  const buf = await sharp(readFileSync(file)).resize(12).webp({ quality: 20 }).toBuffer()
  out[`/images/${key}.webp`] = `data:image/webp;base64,${buf.toString('base64')}`
}

writeFileSync(
  'lib/blurData.js',
  '// GENERATED by scripts/gen-blur.mjs — do not edit by hand.\n' +
    'export const blurData = ' + JSON.stringify(out, null, 2) + '\n'
)

const bytes = Buffer.byteLength(JSON.stringify(out))
console.log(`${Object.keys(out).length} hero placeholders -> lib/blurData.js (${(bytes / 1024).toFixed(1)} KB)`)
if (missing.size) console.log('not found on disk:', [...missing].join(', '))
